# Generated by Django 2.1.5 on 2022-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('formula0', models.CharField(max_length=120)),
                ('formula1', models.CharField(max_length=120)),
                ('formula2', models.CharField(max_length=120)),
            ],
        ),
    ]
