# Generated by Django 2.1.5 on 2022-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truthTable', '0003_exercise2_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise2',
            name='values',
            field=models.CharField(default=False, max_length=120),
            preserve_default=False,
        ),
    ]
